f = {u'contributors': None,
     u'coordinates': None,
     u'created_at': u'Fri Feb 07 23:15:18 +0000 2014',
     u'entities': {u'hashtags': [],
                   u'symbols': [],
                   u'urls': [],
                   u'user_mentions': []},
     u'favorite_count': 0,
     u'favorited': False,
     u'geo': None,
     u'id': 431929188598042624L,
     u'id_str': u'431929188598042624',
     u'in_reply_to_screen_name': None,
     u'in_reply_to_status_id': None,
     u'in_reply_to_status_id_str': None,
     u'in_reply_to_user_id': None,
     u'in_reply_to_user_id_str': None,
     u'lang': u'en',
     u'place': None,
     u'retweet_count': 0,
     u'retweeted': False,
     u'source': u'<a href="http://www.state.gov/" rel="nofollow">Usdosaqi</a>',
     u'text': u'02-08-2014 07:00; PM2.5; 90.0; 169; Unhealthy (at 24-hour exp\
               osure at this level)',
     u'truncated': False,
     u'user': {u'contributors_enabled': False,
               u'created_at': u'Sat Jun 23 04:45:58 +0000 2012',
               u'default_profile': True,
               u'default_profile_image': False,
               u'description': u'MetOne BAM 1020, reporting PM2.5 hourly. For\
                                 mat: pollutant type; concentration; AQI; def\
                                 inition.\r\nOfficial Air Quality Monitor of \
                                 the U.S. Consulate in Shenyang',
               u'favourites_count': 0,
               u'follow_request_sent': False,
               u'followers_count': 271,
               u'following': True,
               u'friends_count': 4,
               u'geo_enabled': False,
               u'id': 615812599,
               u'id_str': u'615812599',
               u'is_translation_enabled': False,
               u'is_translator': False,
               u'lang': u'en',
               u'listed_count': 5,
               u'location': u'Heping District, Shenyang',
               u'name': u'ConGenShenyang',
               u'protected': False,
               u'screen_name': u'Shenyang_Air',
               u'statuses_count': 7399,
               u'time_zone': u'Hawaii',
               u'url': u'http://t.co/r0tfVHohTe',
               u'utc_offset': -36000,
               u'verified': True}}
