# -*- coding: utf-8 -*-
import datetime


m = [{u'data': {u'concentration': 141.0,
      u'display': {u'en': u'Unhealthy (at 24-hour exposure at this level)',
                   u'fr': u''},
      u'index': [195, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-11-2014 07:00; PM2.5; 141.0; 195; Unhealthy \
(at 24-hour exposure at this level)',
      u'reading_id': 433016360931573760L,
      u'source': {u'display_name': u'ConGenShenyang',
                  u'screen_name': u'Shenyang_Air',
                  u'type': u'twitter',
                  u'user_id': 615812599},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 11, 7, 0),
                u'hour_to': None, u'nature': u'hourly'}},
     {u'data': {u'concentration': 84.0,
      u'display': {u'en': u'Unhealthy (at 24-hour exposure at this level)',
                   u'fr': u''},
      u'index': [166, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-11-2014 08:00; PM2.5; 84.0; 166; Unhealthy \
(at 24-hour exposure at this level)',
      u'reading_id': 433031445540372480L,
      u'source': {u'display_name': u'BeijingAir',
                  u'screen_name': u'BeijingAir',
                  u'type': u'twitter',
                  u'user_id': 15527964},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 11, 8, 0),
                u'hour_to': None,
                u'nature': u'hourly'}},
     {u'data': {u'concentration': 77.0,
      u'display': {u'en': u'Unhealthy (at 24-hour exposure at this level)',
                   u'fr': u''},
      u'index': [162, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-11-2014 08:00; PM2.5; 77.0; 162; Unhealthy \
(at 24-hour exposure at this level)',
      u'reading_id': 433031446563786752L,
      u'source': {u'display_name': u'CGChengduAir',
                  u'screen_name': u'CGChengduAir',
                  u'type': u'twitter',
                  u'user_id': 577897347},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 11, 8, 0),
                u'hour_to': None,
                u'nature': u'hourly'}},
     {u'data': {u'concentration': -0.1,
      u'display': {u'en': u'No Data', u'fr': u'Pas de donn\xe9es'},
      u'index': [],
      u'missing': True,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-11-2014 08:00; PM2.5; No Data',
      u'reading_id': 433031447578808320L,
      u'source': {u'display_name': u'GuangzhouAir',
                  u'screen_name': u'Guangzhou_Air',
                  u'type': u'twitter',
                  u'user_id': 304788556},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 11, 8, 0),
                u'hour_to': None,
                u'nature': u'hourly'}},
     {u'data': {u'concentration': 48.0,
      u'display': {u'en': u'Unhealthy for Sensitive Groups \
(at 24-hour exposure at this level)',
                   u'fr': u''},
      u'index': [132, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-11-2014 08:00; PM2.5; 48.0; 132; Unhealthy \
for Sensitive Groups (at 24-hour exposure at this level)',
      u'reading_id': 433031448631578624L,
      u'source': {u'display_name': u'Con Gen ShanghaiAir',
                  u'screen_name': u'CGShanghaiAir',
                  u'type': u'twitter',
                  u'user_id': 562768872},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 11, 8, 0),
                u'hour_to': None,
                u'nature': u'hourly'}},
     {u'data': {u'concentration': 139.0,
      u'display': {u'en': u'Unhealthy (at 24-hour exposure at \
this level)', u'fr': u''},
      u'index': [194, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-11-2014 08:00; PM2.5; 139.0; 194; Unhealthy \
(at 24-hour exposure at this level)',
      u'reading_id': 433031449638232064L,
      u'source': {u'display_name': u'ConGenShenyang',
                  u'screen_name': u'Shenyang_Air',
                  u'type': u'twitter',
                  u'user_id': 615812599},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 11, 8, 0),
                u'hour_to': None, u'nature': u'hourly'}},
     {u'data': {u'concentration': 61.0,
      u'display': {u'en': u'Unhealthy (at 24-hour exposure \
at this level)', u'fr': u''},
      u'index': [154, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-10-2014 03:00; PM2.5; 61.0; 154; Unhealthy \
(at 24-hour exposure at this level)',
      u'reading_id': 432593571661631488L,
      u'source': {u'display_name': u'ConGenShenyang',
                  u'screen_name': u'Shenyang_Air',
                  u'type': u'twitter',
                  u'user_id': 615812599},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 10, 3, 0),
                u'hour_to': None, u'nature': u'hourly'}},
     {u'data': {u'concentration': 13.0,
      u'display': {u'en': u'Moderate (at 24-hour exposure at this level)',
                   u'fr': u''},
      u'index': [53, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-10-2014 04:00; PM2.5; 13.0; 53; Moderate \
(at 24-hour exposure at this level)',
      u'reading_id': 432608665351118849L,
      u'source': {u'display_name': u'BeijingAir',
                  u'screen_name': u'BeijingAir',
                  u'type': u'twitter',
                  u'user_id': 15527964},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 10, 4, 0),
                u'hour_to': None, u'nature': u'hourly'}},
     {u'data': {u'concentration': 57.0,
      u'display': {u'en': u'Unhealthy (at 24-hour exposure at this level)',
                   u'fr': u''},
      u'index': [152, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-10-2014 04:00; PM2.5; 57.0; 152; Unhealthy \
(at 24-hour exposure at this level)',
      u'reading_id': 432608666437423104L,
      u'source': {u'display_name': u'CGChengduAir',
                  u'screen_name': u'CGChengduAir',
                  u'type': u'twitter',
                  u'user_id': 577897347},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 10, 4, 0),
                u'hour_to': None, u'nature': u'hourly'}},
     {u'data': {u'concentration': 17.0,
      u'display': {u'en': u'Moderate (at 24-hour exposure at this level)',
                   u'fr': u''},
      u'index': [61, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-10-2014 04:00; PM2.5; 17.0; 61; Moderate (at \
24-hour exposure at this level)',
      u'reading_id': 432608667569881088L,
      u'source': {u'display_name': u'GuangzhouAir',
                  u'screen_name': u'Guangzhou_Air',
                  u'type': u'twitter',
                  u'user_id': 304788556},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 10, 4, 0),
                u'hour_to': None, u'nature': u'hourly'}},
     {u'data': {u'concentration': 31.0,
      u'display': {u'en': u'Moderate (at 24-hour exposure at this level)',
                   u'fr': u''},
      u'index': [91, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-10-2014 04:00; PM2.5; 31.0; 91; Moderate \
(at 24-hour exposure at this level)',
      u'reading_id': 432608668555563008L,
      u'source': {u'display_name': u'Con Gen ShanghaiAir',
                  u'screen_name': u'CGShanghaiAir',
                  u'type': u'twitter',
                  u'user_id': 562768872},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 10, 4, 0),
                u'hour_to': None, u'nature': u'hourly'}},
     {u'data': {u'concentration': 59.0,
      u'display': {u'en': u'Unhealthy (at 24-hour exposure at this level)',
                   u'fr': u''},
      u'index': [153, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-10-2014 04:00; PM2.5; 59.0; 153; Unhealthy \
(at 24-hour exposure at this level)',
      u'reading_id': 432608669578952704L,
      u'source': {u'display_name': u'ConGenShenyang',
                  u'screen_name': u'Shenyang_Air',
                  u'type': u'twitter',
                  u'user_id': 615812599},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 10, 4, 0),
                u'hour_to': None, u'nature': u'hourly'}},
     {u'data': {u'concentration': 57.0,
      u'display': {u'en': u'Unhealthy (at 24-hour exposure at this level)',
                   u'fr': u''},
      u'index': [152, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-08-2014 13:00; PM2.5; 57.0; 152; Unhealthy \
(at 24-hour exposure at this level)',
      u'reading_id': 432019784369074176L,
      u'source': {u'display_name': u'ConGenShenyang',
                  u'screen_name': u'Shenyang_Air',
                  u'type': u'twitter',
                  u'user_id': 615812599},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 8, 13, 0),
                u'hour_to': None, u'nature': u'hourly'}},
     {u'data': {u'concentration': 57.0,
      u'display': {u'en': u'Unhealthy (at 24-hour exposure at this level)',
                   u'fr': u''},
      u'index': [152, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-08-2014 13:00; PM2.5; 57.0; 152; Unhealthy \
(at 24-hour exposure at this level)',
      u'reading_id': 432019782871699458L,
      u'source': {u'display_name': u'Con Gen ShanghaiAir',
                  u'screen_name': u'CGShanghaiAir',
                  u'type': u'twitter',
                  u'user_id': 562768872},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 8, 13, 0),
                u'hour_to': None, u'nature': u'hourly'}},
     {u'data': {u'concentration': 22.0,
      u'display': {u'en': u'Moderate (at 24-hour exposure at this level)',
                   u'fr': u''},
      u'index': [72, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-08-2014 13:00; PM2.5; 22.0; 72; Moderate \
(at 24-hour exposure at this level)',
      u'reading_id': 432019781697273856L,
      u'source': {u'display_name': u'GuangzhouAir',
                  u'screen_name': u'Guangzhou_Air',
                  u'type': u'twitter',
                  u'user_id': 304788556},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 8, 13, 0),
                u'hour_to': None, u'nature': u'hourly'}},
     {u'data': {u'concentration': 84.3,
      u'display': {u'en': u'Unhealthy', u'fr': u''},
      u'index': [166, u'AQI'],
      u'missing': False,
      u'pollutant': u'PM2.5'},
      u'raw': u'02-07-2014 12:00 to 02-08-2014 11:59; PM2.5 24hr \
avg; 84.3; 166; Unhealthy',
      u'reading_id': 432004689362558976L,
      u'source': {u'display_name': u'ConGenShenyang',
                  u'screen_name': u'Shenyang_Air',
                  u'type': u'twitter',
                  u'user_id': 615812599},
      u'type': {u'hour_from': datetime.datetime(2014, 2, 7, 12, 0),
                u'hour_to': datetime.datetime(2014, 2, 8, 11, 59),
                u'nature': u'24havg'}}]
